{% set name = "sycomore" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lamyj/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 255a0c5b6a0e0c5ca5ca21e082a002502a5a4a84584890641ec30cd15b2ad10b
  patches:
    - xsimd-8.patch

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - pybind11
    - python
    - numpy >=1.16
    - xsimd
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - sycomore

about:
  home: https://github.com/lamyj/{{ name|lower }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: MRI Simulation toolkit

  description: |
    Sycomore is an MRI simulation toolkit providing Bloch simulation, Extended 
    Phase Graphs (EPG) (both regular and discrete, including 3D), and 
    Configuration Models. Sycomore is a Python packge in which all 
    computationnaly-intensive operations are run by a C++ backend, providing a 
    very fast runtime.
  doc_url: https://{{ name|lower }}.readthedocs.io/
  dev_url: https://github.com/lamyj/{{ name|lower }}

extra:
  recipe-maintainers:
    - lamyj
