{% set name = "sycomore" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lamyj/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c3c498bb2fd9b8b8f839948229f8bf019f89e57cacd5b49cb9e447d1e3240d11

build:
  number: 0
  skip: True  # [py<=35 or (win and vc<14)]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - pybind11
    - python
    - setuptools
    - setuptools_scm
    - pip
    - numpy >=1.16
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - sycomore

about:
  home: https://github.com/lamyj/{{ name|lower }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'MRI Simulation toolkit'

  description: |
    Sycomore is an MRI simulation toolkit providing Bloch simulation, Extended 
    Phase Graphs (EPG) (both regular and discrete, including 3D), and 
    Configuration Models. Sycomore is a Python packge in which all 
    computationnaly-intensive operations are run by a C++ backend, providing a 
    very fast runtime.
  doc_url: https://{{ name|lower }}.readthedocs.io/
  dev_url: https://github.com/lamyj/{{ name|lower }}

extra:
  recipe-maintainers:
    - lamyj
