{% set name = "sycomore" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lamyj/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fda71837669d1b3edb27cfdc4d39e6707aa37169358dc3efa3983e0e71e3ba0c

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - pybind11
    - python
    - numpy >=1.16
    # Pin version on macOS due to https://github.com/xtensor-stack/xsimd/pull/811
    - xsimd <9.0.0|>9.0.1  # [osx]
    - xsimd  # [not osx]
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - sycomore

about:
  home: https://github.com/lamyj/{{ name|lower }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: MRI Simulation toolkit

  description: |
    Sycomore is an MRI simulation toolkit providing Bloch simulation, Extended 
    Phase Graphs (EPG) (both regular and discrete, including 3D), and 
    Configuration Models. Sycomore is a Python packge in which all 
    computationnaly-intensive operations are run by a C++ backend, providing a 
    very fast runtime.
  doc_url: https://{{ name|lower }}.readthedocs.io/
  dev_url: https://github.com/lamyj/{{ name|lower }}

extra:
  recipe-maintainers:
    - lamyj
